apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/environment: prod

resources:
  - ../../../base/instance

namespace: aap

patches:
  - path: aap-patch.yaml
