apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Deploy with: oc apply -k argocd/
# Note: Repository URL is configured directly in the YAML files

resources:
  - projects/aap-project.yaml
  - applicationsets/aap.yaml
  - bootstrap/aap-bootstrap.yaml
