apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/environment: dev

resources:
  - ../../../base/operator

namespace: aap-dev

patches:
  # Operator channel - change version here
  - target:
      kind: Subscription
      name: ansible-automation-platform-operator
    patch: |
      - op: replace
        path: /spec/channel
        value: stable-2.6
  # OperatorGroup must target this namespace
  - target:
      kind: OperatorGroup
      name: aap-operator-group
    patch: |
      - op: replace
        path: /spec/targetNamespaces/0
        value: aap-dev
