apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/environment: prod

resources:
  - ../../../base/operator

namespace: aap

patches:
  # Operator channel - change version here
  - target:
      kind: Subscription
      name: ansible-automation-platform-operator
    patch: |
      - op: replace
        path: /spec/channel
        value: stable-2.6
